### PR TITLE
fix: make job name sanatization conform to k8s naming rules

### LINKED ISSUE #236: Job name
**Describe the bug**
We use Azure for our git repos. We use projects and project groups with spaces and other special characters. When the operator tries to spawn k8s jobs, the creation errors due to invalid characters in the job name.

**To Reproduce**
1. Setup renovate-operator connected to an Azure Devops environment with project names that don't follow k8s naming convention requirements.
2. Attempt to trigger a project with invalid names
3. See error

**Expected behavior**
The operator should translate project names into acceptable job names potentially replacing invalid characters with '-'

**Screenshots & Logs**
If applicable, add screenshots or logs to help explain your problem.

**Information (please complete the following information):**
 - Kubernetes Version Latest
 - Version 3.10.0

### PR DESCRIPTION
**Pull request by wittdennis**
Fixes #236

### CODE REVIEW

File: src/internal/utils/jobNames_test.go [hunk 1]
```diff
@@ -61,14 +61,14 @@ func TestRenovateJob_JobNames(t *testing.T) {
 			name:              "complex project name",
 			jobName:           "renovate",
 			project:           "Org/.github",
-			expectedExecutor:  "renovate-org--github-3ff30a25",
```
Comment (lukashankeln) [inline src/internal/utils/jobNames_test.go]: This is a breaking change...

Depending on your configuration this might result in Jobs not getting deleted

Comment (wittdennis) [reply src/internal/utils/jobNames_test.go]: Fair enough. I marked the change as breaking. Would make sense then to bundle with #241
